### ISSUE TITLE
Encoding::UndefinedConversionError error=\"\\\"\\\\xC2\\\" from ASCII-8BIT to UTF-8\"\n"

### ISSUE THREAD

**Issue by pangxudong** [roffe/kube-gelf#17] opened 2018-03-20 04:41 UTC
My k8s version is 1.8.4, and I changed daemonset.yaml of kube-gelf with `apiVersion: apps/v1beta2`, but meet up with this error:

```
{"log":"2018-03-20 04:38:05 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-03-20 04:38:06 +0000 chunk=\"567d0a3a7cd0faf6bba0db19c68087f8\" error_class=Encoding::UndefinedConversionError error=\"\\\"\\\\xC2\\\" from ASCII-8BIT to UTF-8\"\n","stream":"stdout","time":"2018-03-20T04:38:05.355760692Z"}
{"log":"  2018-03-20 04:38:05 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/gelf-3.0.0/lib/gelf/notifier.rb:257:in `encode'\n","stream":"stdout","time":"2018-03-20T04:38:05.355816847Z"}
{"log":"  2018-03-20 04:38:05 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/gelf-3.0.0/lib/gelf/notifier.rb:257:in `to_json'\n","stream":"stdout","time":"2018-03-20T04:38:05.355828247Z"}
{"log":"  2018-03-20 04:38:05 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/gelf-3.0.0/lib/gelf/notifier.rb:257:in `serialize_hash'\n","stream":"stdout","time":"2018-03-20T04:38:05.355837241Z"}
{"log":"  2018-03-20 04:38:05 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/gelf-3.0.0/lib/gelf/notifier.rb:227:in `datagrams_from_hash'\n","stream":"stdout","time":"2018-03-20T04:38:05.355846439Z"}
{"log":"  2018-03-20 04:38:05 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/gelf-3.0.0/lib/gelf/notifier.rb:162:in `notify_with_level!'\n","stream":"stdout","time":"2018-03-20T04:38:05.35585497Z"}
{"log":"  2018-03-20 04:38:05 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/gelf-3.0.0/lib/gelf/notifier.rb:119:in `notify!'\n","stream":"stdout","time":"2018-03-20T04:38:05.355862863Z"}
{"log":"  2018-03-20 04:38:05 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-gelf-hs-1.0.4/lib/fluent/plugin/out_gelf.rb:79:in `block in write'\n","stream":"stdout","time":"2018-03-20T04:38:05.355870418Z"}
{"log":"  2018-03-20 04:38:05 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/event.rb:323:in `each'\n","stream":"stdout","time":"2018-03-20T04:38:05.355879204Z"}
{"log":"  2018-03-20 04:38:05 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/event.rb:323:in `block in each'\n","stream":"stdout","time":"2018-03-20T04:38:05.355888242Z"}
{"log":"  2018-03-20 04:38:05 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/plugin/buffer/memory_chunk.rb:80:in `open'\n","stream":"stdout","time":"2018-03-20T04:38:05.355896336Z"}
{"log":"  2018-03-20 04:38:05 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/plugin/buffer/memory_chunk.rb:80:in `open'\n","stream":"stdout","time":"2018-03-20T04:38:05.36106632Z"}
{"log":"  2018-03-20 04:38:05 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/event.rb:322:in `each'\n","stream":"stdout","time":"2018-03-20T04:38:05.361081251Z"}
{"log":"  2018-03-20 04:38:05 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-gelf-hs-1.0.4/lib/fluent/plugin/out_gelf.rb:78:in `write'\n","stream":"stdout","time":"2018-03-20T04:38:05.361087536Z"}
{"log":"  2018-03-20 04:38:05 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/compat/output.rb:131:in `write'\n","stream":"stdout","time":"2018-03-20T04:38:05.361095174Z"}
{"log":"  2018-03-20 04:38:05 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/plugin/output.rb:1094:in `try_flush'\n","stream":"stdout","time":"2018-03-20T04:38:05.361100737Z"}
{"log":"  2018-03-20 04:38:05 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/plugin/output.rb:1319:in `flush_thread_run'\n","stream":"stdout","time":"2018-03-20T04:38:05.36110635Z"}
{"log":"  2018-03-20 04:38:05 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/plugin/output.rb:439:in `block (2 levels) in start'\n","stream":"stdout","time":"2018-03-20T04:38:05.361113455Z"}
{"log":"  2018-03-20 04:38:05 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'\n","stream":"stdout","time":"2018-03-20T04:38:05.361118985Z"}
{"log":"2018-03-20 04:38:07 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-03-20 04:38:06 +0000 chunk=\"567d0a3a7cd0faf6bba0db19c68087f8\" error_class=Encoding::UndefinedConversionError error=\"\\\"\\\\xC2\\\" from ASCII-8BIT to UTF-8\"\n","stream":"stdout","time":"2018-03-20T04:38:07.764276396Z"}
```

**Comment by roffe** [comment] 2018-03-20 13:07
Seems to be a duplicate of https://github.com/roffe/kube-gelf/issues/15
Same question here. Can you see any non ascii characters / non utf8 characters in your logs?

**Closed** 2018-12-10 21:15 UTC
